// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrAXGfPEUsAmR-IhmM7Rm-1KCyMiadEM',
    appId: '1:739714672609:web:f06468576d5bf9a82154a0',
    messagingSenderId: '739714672609',
    projectId: 'flutter001-268d1',
    authDomain: 'flutter001-268d1.firebaseapp.com',
    storageBucket: 'flutter001-268d1.firebasestorage.app',
    measurementId: 'G-21JNZRQPJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nb_a0gVBupINThLry6bJYJWn7b8xgzo',
    appId: '1:739714672609:android:422f5ab109f949502154a0',
    messagingSenderId: '739714672609',
    projectId: 'flutter001-268d1',
    storageBucket: 'flutter001-268d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5cUFgVscA33qrfd9EgPDMXS-wZKHaNos',
    appId: '1:739714672609:ios:6ca8c5fa28d48c132154a0',
    messagingSenderId: '739714672609',
    projectId: 'flutter001-268d1',
    storageBucket: 'flutter001-268d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5cUFgVscA33qrfd9EgPDMXS-wZKHaNos',
    appId: '1:739714672609:ios:6ca8c5fa28d48c132154a0',
    messagingSenderId: '739714672609',
    projectId: 'flutter001-268d1',
    storageBucket: 'flutter001-268d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdrAXGfPEUsAmR-IhmM7Rm-1KCyMiadEM',
    appId: '1:739714672609:web:4b6f8beeed5b47552154a0',
    messagingSenderId: '739714672609',
    projectId: 'flutter001-268d1',
    authDomain: 'flutter001-268d1.firebaseapp.com',
    storageBucket: 'flutter001-268d1.firebasestorage.app',
    measurementId: 'G-41HP1RL0VS',
  );
}
